language: ruby

services:
  - redis-server

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.2
  - jruby-19mode
  - rbx-2

services:
  - redis-server

before_script:
  - git submodule update --init

script: bundle exec rspec

env: TRAVIS=1
